OI-201,186,176,164,125,182,183,193,188,193,197,199, 00
istolar/openideal_distribution pull request #148
Opened 2020-09-04 16:21 UTC by nvelychenko

2020-09-05 12:17 UTC, db-Matroskeen requested changes

2020-09-05 12:17 UTC, db-Matroskeen commented on themes/openideal_theme/scss/components/_message.scss
> +    &:after {
This part is duplicated multiple times, let's avoid this.

2020-09-05 12:17 UTC, db-Matroskeen commented on themes/openideal_theme/scss/components/_import.scss
> +@import "_default_user_forms";
Is `_` at the beginning required?

2020-09-06 07:43 UTC, nvelychenko commented on themes/openideal_theme/scss/components/_import.scss
> +@import "_default_user_forms";
https://stackoverflow.com/a/34890015

2020-09-06 12:36 UTC, merged